//! Spec strength: do the proved properties determine the model?
//!
//! `@proves` says the model has a property. It says nothing about how much that
//! property rules out, and the gap is enormous: `discount s ≤ s` is a genuine
//! machine-checked theorem that the constant-zero function also satisfies.
//! Unqualified, a proof level is what a testing level would be without a
//! coverage floor.
//!
//! The relational specification is the *set of proved theorems*, and the
//! question is whether everything satisfying them is this model.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

use super::annotation::{Qualifier, Role};
use super::index::Index;

/// What is known about one modelled clause's strength.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", rename_all_fields = "camelCase")]
pub enum Strength {
    /// A pinning theorem exists and is finished.
    ///
    /// `theorem` is a keyword in the model's language, where this field is
    /// spelled `theoremName`; the wire name follows the model.
    Pinned { theorem_name: String },
    /// A pinning theorem exists and is not finished.
    ///
    /// @implements REQ-STRENGTH.attempted_distinguished
    Attempted { theorem_name: String },
    /// Nobody has said anything. The default, and not a failure — but not a
    /// pass either, which is the whole point of naming the state.
    ///
    /// @implements REQ-STRENGTH.open_is_the_default
    Open,
    /// Declared unpinnable, with a reason.
    ///
    /// Some functions genuinely are not determined by their declared inputs.
    /// Saying so once, with a reason, beats an obligation that stays open
    /// forever and teaches everyone to ignore the column it sits in.
    ///
    /// @implements REQ-STRENGTH.nondeterministic_declared
    Nondeterministic { reason: String },
}

impl Strength {
    /// Whether this may be presented as a pass. `Open` may not.
    pub fn is_settled(&self) -> bool {
        matches!(self, Strength::Pinned { .. } | Strength::Nondeterministic { .. })
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Strength::Pinned { .. } => "pinned",
            Strength::Attempted { .. } => "attempted",
            Strength::Open => "open",
            Strength::Nondeterministic { .. } => "nondeterministic",
        }
    }
}

/// The obligation for one modelled declaration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Obligation {
    /// The model symbol the question is about.
    pub symbol: String,
    /// Clauses this declaration models. The question is about the *function*,
    /// so one declaration owes one obligation however many clauses it serves.
    pub clauses: Vec<(String, Option<String>)>,
    /// Theorems proved about it, which together are the specification.
    pub theorems: Vec<String>,
    pub strength: Strength,
}

/// `Obligation::lean_source`, over an owned argument.
///
/// @implements REQ-STRENGTH.obligation_generated
/// @implements REQ-STRENGTH.not_proved_by_us
/// @drt REQ-STRENGTH.obligation_generated
/// @drt REQ-STRENGTH.not_proved_by_us
pub fn obligation_source(obligation: Obligation) -> String {
    obligation.lean_source()
}

impl Obligation {
    /// The Lean source of the obligation.
    ///
    /// Generated, never discharged: proving it is the human's part, and while
    /// nobody has, the honest report is "open" rather than "fine". The
    /// generated text therefore ends in `sorry`, so the kernel agrees it is
    /// unproved until somebody does the work.
    ///
    /// @implements REQ-STRENGTH.obligation_generated
    /// @implements REQ-STRENGTH.not_proved_by_us
    pub fn lean_source(&self) -> String {
        let name = self.symbol.replace("::", "_").replace('.', "_");
        let spec = if self.theorems.is_empty() {
            "  -- No theorems are proved about this model, so the specification is empty\n  \
             -- and everything satisfies it: this obligation is unprovable as it stands.\n  True"
                .to_string()
        } else {
            self.theorems
                .iter()
                .map(|t| format!("  -- from {t}\n  True"))
                .collect::<Vec<_>>()
                .join(" ∧\n")
        };

        format!(
            "-- Generated by TraceLean. The proof is yours to write.\n\
             -- Does the specification determine the model, or merely constrain it?\n\
             def Spec_{name} (f : _) : Prop :=\n{spec}\n\n\
             /-- @pins {} -/\n\
             theorem pins_{name} :\n\
             \x20   ∀ f g, Spec_{name} f → Spec_{name} g → f = g := by\n\
             \x20 sorry\n",
            self.clauses
                .iter()
                .map(|(req, clause)| match clause {
                    Some(c) => format!("{req}.{c}"),
                    None => req.clone(),
                })
                .collect::<Vec<_>>()
                .join(" "),
        )
    }
}

/// A link reduced to what strength depends on: who claims what about which
/// declaration, and whether that declaration was declared unpinnable.
///
/// The rest of a link — its body hash, its line, its file — says nothing about
/// whether a specification determines a model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StrengthLink {
    pub role: Role,
    pub req_id: String,
    pub clause: Option<String>,
    /// Anchor identity of the declaration this link points at.
    pub anchor: String,
    /// The reason given, when the model was declared unpinnable.
    pub nondeterministic: Option<String>,
}

/// Every modelled declaration's obligation, and where it stands.
///
/// @implements REQ-STRENGTH.qualifies_proof
pub fn obligations(index: &Index) -> Vec<Obligation> {
    obligations_from(
        index
            .links
            .iter()
            .map(|link| StrengthLink {
                role: link.role,
                req_id: link.req_id.clone(),
                clause: link.clause.clone(),
                anchor: link.anchor.ident(),
                nondeterministic: match &link.qualifier {
                    Some(Qualifier::Nondeterministic { reason }) => {
                        Some(reason.clone().unwrap_or_else(|| "no reason given".into()))
                    }
                    _ => None,
                },
            })
            .collect(),
    )
}

/// The decision, over nothing but the links.
///
/// Separated from the index so it is a function of stated claims alone: the
/// shell projects, this decides.
///
/// @implements ARCH-CORE-SHELL.decision_total
/// @implements REQ-STRENGTH.qualifies_proof
/// @implements REQ-STRENGTH.open_is_the_default
/// @implements REQ-STRENGTH.attempted_distinguished
/// @implements REQ-STRENGTH.nondeterministic_declared
/// @drt REQ-STRENGTH.qualifies_proof
/// @drt REQ-STRENGTH.open_is_the_default
/// @drt REQ-STRENGTH.attempted_distinguished
/// @drt REQ-STRENGTH.nondeterministic_declared
pub fn obligations_from(links: Vec<StrengthLink>) -> Vec<Obligation> {
    // Model symbol -> the clauses it models.
    let mut by_symbol: BTreeMap<String, Vec<(String, Option<String>)>> = BTreeMap::new();
    let mut theorems: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut pins: BTreeMap<String, String> = BTreeMap::new();
    let mut nondeterministic: BTreeMap<String, String> = BTreeMap::new();

    for link in &links {
        let key = (link.req_id.clone(), link.clause.clone());
        match link.role {
            Role::Models => {
                by_symbol.entry(link.anchor.clone()).or_default().push(key);
                if let Some(reason) = &link.nondeterministic {
                    nondeterministic.insert(link.anchor.clone(), reason.clone());
                }
            }
            Role::Proves => {
                // A theorem is attributed to the model it is about, which is
                // the model serving the same clause.
                for other in &links {
                    if other.role == Role::Models
                        && other.req_id == link.req_id
                        && other.clause == link.clause
                    {
                        theorems.entry(other.anchor.clone()).or_default().push(link.anchor.clone());
                    }
                }
            }
            Role::Pins => {
                for other in &links {
                    if other.role == Role::Models
                        && other.req_id == link.req_id
                        && other.clause == link.clause
                    {
                        pins.insert(other.anchor.clone(), link.anchor.clone());
                    }
                }
            }
            _ => {}
        }
    }

    let mut out: Vec<Obligation> = by_symbol
        .into_iter()
        .map(|(symbol, mut clauses)| {
            clauses.sort();
            clauses.dedup();
            let mut proved = theorems.get(&symbol).cloned().unwrap_or_default();
            proved.sort();
            proved.dedup();

            let strength = match nondeterministic.get(&symbol) {
                Some(reason) => Strength::Nondeterministic { reason: reason.clone() },
                None => match pins.get(&symbol) {
                    // A pinning theorem that exists is not yet a pinning
                    // theorem that is finished; only the kernel can say which,
                    // and that is recorded as evidence rather than guessed here.
                    Some(theorem) => Strength::Attempted { theorem_name: theorem.clone() },
                    None => Strength::Open,
                },
            };

            Obligation { symbol, clauses, theorems: proved, strength }
        })
        .collect();
    out.sort_by(|a, b| a.symbol.cmp(&b.symbol));
    out
}

/// Mark an obligation pinned, on the strength of a kernel-checked proof.
///
/// Separate from `obligations` because only a build can establish it: a `@pins`
/// annotation says somebody wrote the theorem, and a passing build says the
/// kernel accepted it.
///
/// @implements REQ-STRENGTH.attempted_distinguished
pub fn confirm(obligation: &mut Obligation, proved: bool) {
    if let Strength::Attempted { theorem_name } = obligation.strength.clone() {
        if proved {
            obligation.strength = Strength::Pinned { theorem_name };
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn obligation(theorems: &[&str]) -> Obligation {
        Obligation {
            symbol: "formal/TraceLean/Evidence.lean::TraceLean::assurance".into(),
            clauses: vec![("REQ-EVID".into(), Some("weakest_link".into()))],
            theorems: theorems.iter().map(|t| t.to_string()).collect(),
            strength: Strength::Open,
        }
    }

    /// @tests REQ-STRENGTH.obligation_generated
    #[test]
    fn the_generated_obligation_asks_whether_the_spec_determines_the_model() {
        let source = obligation(&["assurance_le_bond"]).lean_source();
        assert!(source.contains("∀ f g,"), "{source}");
        assert!(source.contains("→ f = g"), "{source}");
        assert!(source.contains("@pins REQ-EVID.weakest_link"), "{source}");
    }

    /// @tests REQ-STRENGTH.not_proved_by_us
    #[test]
    fn the_obligation_arrives_unproved() {
        assert!(obligation(&["t"]).lean_source().contains("sorry"));
    }

    /// A model with no theorems has an empty specification, which everything
    /// satisfies — and the generated text says so rather than looking provable.
    #[test]
    fn no_theorems_is_named_as_an_empty_specification() {
        let source = obligation(&[]).lean_source();
        assert!(source.contains("specification is empty"), "{source}");
    }

    /// @tests REQ-STRENGTH.open_is_the_default
    #[test]
    fn open_is_not_a_pass() {
        assert!(!Strength::Open.is_settled());
        assert!(Strength::Pinned { theorem_name: "t".into() }.is_settled());
        assert!(Strength::Nondeterministic { reason: "a clock".into() }.is_settled());
    }

    /// @tests REQ-STRENGTH.attempted_distinguished
    #[test]
    fn writing_the_theorem_is_not_the_same_as_proving_it() {
        let mut attempted = obligation(&[]);
        attempted.strength = Strength::Attempted { theorem_name: "pins_x".into() };
        assert!(!attempted.strength.is_settled(), "unfinished is not settled");

        confirm(&mut attempted, false);
        assert_eq!(attempted.strength.as_str(), "attempted");

        confirm(&mut attempted, true);
        assert_eq!(attempted.strength.as_str(), "pinned");
    }

    /// Confirming cannot promote something nobody attempted.
    #[test]
    fn confirming_an_open_obligation_changes_nothing() {
        let mut open = obligation(&[]);
        confirm(&mut open, true);
        assert_eq!(open.strength, Strength::Open);
    }
}
