/-
  Spec-strength obligations, generated by TraceLean.

  Each set of proved properties gets one question: do they determine the
  model, or merely constrain it? TraceLean can state the question. Only a
  person can answer it, so every obligation arrives as `sorry` and is
  reported as open until somebody proves or refutes it.

  This file is a scaffold: it is written once and never overwritten, because
  the proofs you add here are the point.
-/
import Checkout
import CheckoutProofs

set_option linter.unusedVariables false
open Checkout

/-- The properties proved about `discountCents`, as a predicate over candidate
    functions. Generated from the proof links for REQ-DISCOUNT.tiers, REQ-DISCOUNT.rounding: discount_le_subtotal. -/
def Spec_discountCents (f : Nat → Nat) : Prop :=
  (∀ (subtotal : Nat), f subtotal ≤ subtotal)

/-- The model satisfies its own abstracted specification.

    Generated, and a guard on the generation itself: the predicate above is
    built by rewriting the theorems' statements, and if that rewriting went
    wrong this stops elaborating. -/
theorem discountCents_models_its_spec : Spec_discountCents Checkout.discountCents := by
  unfold Spec_discountCents
  exact discount_le_subtotal

/-- @pins REQ-DISCOUNT.tiers
    @pins REQ-DISCOUNT.rounding

    Do those properties *determine* `discountCents`, or merely constrain it?
    Proving this says anything satisfying them is that function. Leaving it
    `sorry` says nobody knows yet, which TraceLean reports as open rather than
    as passing.

    If it turns out to be false, that is the more useful answer: exhibit a
    second function satisfying `Spec_discountCents` and differing from `Checkout.discountCents`,
    and the witness shows exactly which behaviour the proofs fail to rule out.

    If `discountCents` is genuinely not determined by its inputs -- randomness,
    a clock, concurrency -- delete this and write the nondeterministic
    qualifier, with a reason, beside the model instead. -/
theorem discountCents_pinned :
    ∀ f g, Spec_discountCents f → Spec_discountCents g → f = g := by
  sorry

/-- The properties proved about `shippingCents`, as a predicate over candidate
    functions. Generated from the proof links for REQ-SHIPPING.free, REQ-SHIPPING.flat, REQ-SHIPPING.remote: free_above_threshold, flat_below_threshold, remote_surcharge_survives_free_shipping, remote_below_threshold. -/
def Spec_shippingCents (f : Nat → Bool → Nat) : Prop :=
  (∀ (afterDiscount : Nat) (h : afterDiscount ≥ 10000), f afterDiscount false = 0) ∧
  (∀ (afterDiscount : Nat) (h : afterDiscount < 10000), f afterDiscount false = 599) ∧
  (∀ (afterDiscount : Nat)
    (h : afterDiscount ≥ 10000), f afterDiscount true = 400) ∧
  (∀ (afterDiscount : Nat) (h : afterDiscount < 10000), f afterDiscount true = 999)

/-- The model satisfies its own abstracted specification.

    Generated, and a guard on the generation itself: the predicate above is
    built by rewriting the theorems' statements, and if that rewriting went
    wrong this stops elaborating. -/
theorem shippingCents_models_its_spec : Spec_shippingCents Checkout.shippingCents := by
  unfold Spec_shippingCents
  exact ⟨free_above_threshold, flat_below_threshold, remote_surcharge_survives_free_shipping, remote_below_threshold⟩

/-- @pins REQ-SHIPPING.free
    @pins REQ-SHIPPING.flat
    @pins REQ-SHIPPING.remote

    Do those properties *determine* `shippingCents`, or merely constrain it?
    Proving this says anything satisfying them is that function. Leaving it
    `sorry` says nobody knows yet, which TraceLean reports as open rather than
    as passing.

    If it turns out to be false, that is the more useful answer: exhibit a
    second function satisfying `Spec_shippingCents` and differing from `Checkout.shippingCents`,
    and the witness shows exactly which behaviour the proofs fail to rule out.

    If `shippingCents` is genuinely not determined by its inputs -- randomness,
    a clock, concurrency -- delete this and write the nondeterministic
    qualifier, with a reason, beside the model instead. -/
theorem shippingCents_pinned :
    ∀ f g, Spec_shippingCents f → Spec_shippingCents g → f = g := by
  -- Proved rather than left open: the four properties partition the input
  -- space, so two functions satisfying them agree everywhere.
  intro f g hf hg
  funext a b
  obtain ⟨f0, f1, f2, f3⟩ := hf
  obtain ⟨g0, g1, g2, g3⟩ := hg
  cases b with
  | false =>
    by_cases h : a ≥ 10000
    · rw [f0 a h, g0 a h]
    · rw [f1 a (by omega), g1 a (by omega)]
  | true =>
    by_cases h : a ≥ 10000
    · rw [f2 a h, g2 a h]
    · rw [f3 a (by omega), g3 a (by omega)]

