//! Generating and building the Lean side of a differential test.
//!
//! The model is ordinary compiled Lean, so a case costs microseconds. Only the
//! thin `main` that decodes a case, calls the model and encodes the reply has to
//! be generated — and it is generated into a package of its own, because a
//! project's build files are something a person maintains.

use std::path::{Path, PathBuf};

/// One op, and the Lean expression that answers it.
#[derive(Debug, Clone, PartialEq)]
pub struct LeanEntry {
    pub op: String,
    /// Fully qualified model function, e.g. `TraceLean.assurance`.
    pub function: String,
    /// Input field names to pass, in argument order. Empty means the function
    /// takes no arguments.
    pub arguments: Vec<String>,
}

/// @implements REQ-DRT-LEAN.project_untouched
pub fn package_dir(root: &Path) -> PathBuf {
    root.join(".tracelean").join("drt-lean")
}

/// Whether a Lean toolchain is available.
///
/// A missing toolchain is a first-class explained state — the difference
/// between "this is broken" and "this is not set up yet".
///
/// @implements REQ-DRT-LEAN.toolchain_explained
pub fn toolchain() -> Result<(), String> {
    for tool in ["lean", "lake"] {
        if which(tool).is_none() {
            return Err(format!(
                "no `{tool}` on PATH. Install elan (https://github.com/leanprover/elan) \
                 so the model runner can be built."
            ));
        }
    }
    Ok(())
}

fn which(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|dir| dir.join(name))
        .find(|candidate| candidate.is_file())
}

/// The generated package's lakefile, requiring the project's Lean package by
/// path.
///
/// @implements REQ-DRT-LEAN.generated
pub fn lakefile(model_package: &str, model_path: &str) -> String {
    format!(
        "-- Generated by TraceLean. Edits are overwritten.\n\
         import Lake\n\
         open Lake DSL\n\n\
         package «tracelean-drt» where\n\n\
         require {model_package} from \"{model_path}\"\n\n\
         @[default_target]\n\
         lean_exe «drtRunner» where\n\
         \x20 root := `Main\n"
    )
}

/// The generated `Main.lean`.
///
/// Argument types are never written: `fromJson?` is generic in its result, and
/// elaboration resolves it from the model function's parameter. The binding
/// therefore names no type on this side either.
///
/// Several imports rather than one, so a single runner can answer every op a
/// project declares. One runner per op means one `lake build` per op, and those
/// builds cannot run at once — they all write the same model package's output —
/// so the cost is paid in series.
///
/// Imports are emitted once each, in sorted order, so the same set of entries
/// always produces the same bytes and a rebuild is a no-op.
///
/// @implements REQ-DRT-LEAN.encoding_declared
/// @implements REQ-DRT-PROTO.reply_one_line
/// @implements REQ-DRT-PROTO.case_names_op
/// @implements REQ-DRT-PROTO.runner_shared
pub fn main_lean(imports: &[&str], entries: &[LeanEntry]) -> String {
    let unique: std::collections::BTreeSet<&str> = imports.iter().copied().collect();
    let import_lines: String =
        unique.iter().map(|module| format!("import {module}\n")).collect();
    let mut out = format!(
        "-- Generated by TraceLean. Edits are overwritten.\n\
         import Lean\n\
         {import_lines}\n\
         open Lean\n\n\
         /-- The raw JSON of one input field, or `null` when absent. -/\n\
         def field (input : Json) (name : String) : Json :=\n\
         \x20 (input.getObjVal? name).toOption.getD Json.null\n\n\
         def answer (op : String) (input : Json) : Except String Json :=\n\
         \x20 match op with\n"
    );
    for entry in entries {
        out.push_str(&format!("  | \"{}\" => do\n", entry.op));
        for (i, argument) in entry.arguments.iter().enumerate() {
            out.push_str(&format!(
                "      let a{i} ← (fromJson? (field input \"{argument}\")).mapError\n\
                 \x20         (fun e => s!\"argument `{argument}`: {{e}}\")\n"
            ));
        }
        let args: String = (0..entry.arguments.len())
            .map(|i| format!(" a{i}"))
            .collect();
        out.push_str(&format!("      return toJson ({}{args})\n", entry.function));
    }
    out.push_str(
        "  | other => .error s!\"no binding for op {other}\"\n\n\
         def replyOf (number : Nat) (r : Except String Json) : Json :=\n\
         \x20 match r with\n\
         \x20 | .ok output => Json.mkObj [(\"case\", toJson number), (\"output\", output)]\n\
         \x20 | .error e => Json.mkObj [(\"case\", toJson number), (\"error\", toJson e)]\n\n\
         partial def loop (stream : IO.FS.Stream) : IO Unit := do\n\
         \x20 let line ← stream.getLine\n\
         \x20 if line.isEmpty then return ()\n\
         \x20 if line.trim.isEmpty then loop stream else\n\
         \x20 match Json.parse line with\n\
         \x20 | .error e => (← IO.getStderr).putStrLn s!\"unreadable case: {e}\"; loop stream\n\
         \x20 | .ok case =>\n\
         \x20   let number := ((case.getObjVal? \"case\").toOption.bind\n\
         \x20     (fun j => j.getNat?.toOption)).getD 0\n\
         \x20   let op := ((case.getObjVal? \"op\").toOption.bind\n\
         \x20     (fun j => j.getStr?.toOption)).getD \"\"\n\
         \x20   let input := field case \"input\"\n\
         \x20   IO.println (replyOf number (answer op input)).compress\n\
         \x20   (← IO.getStdout).flush\n\
         \x20   loop stream\n\n\
         def main : IO Unit := do\n\
         \x20 loop (← IO.getStdin)\n",
    );
    out
}

/// Write the generated package if it differs from what would be generated now.
///
/// @implements REQ-DRT-LEAN.generated
pub fn materialize(
    root: &Path,
    imports: &[&str],
    model_package: &str,
    model_path: &str,
    entries: &[LeanEntry],
) -> std::io::Result<PathBuf> {
    let dir = package_dir(root);
    std::fs::create_dir_all(&dir)?;
    write_if_changed(&dir.join("lakefile.lean"), &lakefile(model_package, model_path))?;
    write_if_changed(&dir.join("Main.lean"), &main_lean(imports, entries))?;
    // The toolchain file is copied from the model package so the generated
    // package cannot be built with a different Lean than the model was.
    if let Ok(toolchain) = std::fs::read_to_string(Path::new(model_path).join("lean-toolchain")) {
        write_if_changed(&dir.join("lean-toolchain"), &toolchain)?;
    }
    Ok(dir)
}

fn write_if_changed(path: &Path, contents: &str) -> std::io::Result<()> {
    if std::fs::read_to_string(path).map(|c| c == contents).unwrap_or(false) {
        return Ok(());
    }
    std::fs::write(path, contents)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(op: &str, function: &str) -> LeanEntry {
        LeanEntry {
            op: op.to_string(),
            function: function.to_string(),
            arguments: vec!["records".to_string()],
        }
    }

    /// One runner answers every op it was generated for, from every module
    /// those ops live in.
    ///
    /// @tests REQ-DRT-PROTO.runner_shared
    #[test]
    fn one_runner_imports_every_module_its_ops_live_in() {
        let main = main_lean(
            &["TraceLean.Evidence", "TraceLean.Rollup"],
            &[entry("REQ-EVID.weakest_link", "TraceLean.assurance"), entry("REQ-ROLLUP.min_not_mean", "TraceLean.combine")],
        );
        assert!(main.contains("import TraceLean.Evidence"));
        assert!(main.contains("import TraceLean.Rollup"));
        assert!(main.contains("\"REQ-EVID.weakest_link\""));
        assert!(main.contains("\"REQ-ROLLUP.min_not_mean\""));
    }

    /// The same set of modules always produces the same bytes, whatever order
    /// the bindings were read in and however often a module is named.
    ///
    /// Generation that depended on order would rewrite the shared package on
    /// every run, and rewriting it is what makes the build stop being a no-op.
    ///
    /// @tests ARCH-DETERMINISM.stable_ordering
    #[test]
    fn the_imports_do_not_depend_on_order_or_repetition() {
        let entries = [entry("REQ-EVID.weakest_link", "TraceLean.assurance")];
        let one = main_lean(&["TraceLean.Rollup", "TraceLean.Evidence"], &entries);
        let other =
            main_lean(&["TraceLean.Evidence", "TraceLean.Rollup", "TraceLean.Evidence"], &entries);
        assert_eq!(one, other);
        assert_eq!(one.matches("import TraceLean.Evidence\n").count(), 1);
    }

    /// An op nothing was generated for is an error, not a wrong answer.
    ///
    /// A shared runner is asked for ops it may not have; answering one of them
    /// with another's function is the failure that would look like agreement.
    ///
    /// @tests REQ-DRT-PROTO.case_names_op
    #[test]
    fn an_op_the_runner_does_not_carry_is_refused() {
        let main = main_lean(&["TraceLean.Evidence"], &[entry("REQ-EVID.weakest_link", "f")]);
        assert!(main.contains("no binding for op"));
    }
}
