//! Generating and building the Lean side of a differential test.
//!
//! The model is ordinary compiled Lean — a shallow embedding — so a case costs
//! microseconds and millions of them fit in CI. What has to be generated is the
//! thin `main` that decodes a case, calls the model, and encodes the reply.

use std::path::{Path, PathBuf};

/// Where the generated package lives. A separate package rather than an edit to
/// the user's lakefile, so TraceLean never has to modify a file the project
/// owns.
pub fn package_dir(root: &Path) -> PathBuf {
    root.join(".tracelean").join("drt")
}

/// Whether a Lean toolchain is available at all.
///
/// A missing toolchain is a first-class, explained state — the difference
/// between "this is broken" and "this is not set up yet".
pub fn toolchain() -> Result<Toolchain, String> {
    let lean = find_binary("lean").ok_or_else(|| {
        "No Lean toolchain found. Install elan (https://github.com/leanprover/elan) \
         so `lean` and `lake` are on PATH, then rebuild the model runner."
            .to_string()
    })?;
    let lake = find_binary("lake").ok_or_else(|| {
        "Found `lean` but not `lake`. A lake project is needed to build the model runner."
            .to_string()
    })?;
    let version = std::process::Command::new(&lean)
        .arg("--version")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    Ok(Toolchain { lean, lake, version })
}

#[derive(Debug, Clone)]
pub struct Toolchain {
    pub lean: PathBuf,
    pub lake: PathBuf,
    pub version: String,
}

fn find_binary(name: &str) -> Option<PathBuf> {
    // elan installs here; PATH is the fallback rather than the first guess,
    // because a GUI app often has a narrower PATH than the user's shell.
    if let Ok(home) = std::env::var("HOME") {
        let candidate = PathBuf::from(home).join(".elan/bin").join(name);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    let path = std::env::var("PATH").ok()?;
    std::env::split_paths(&path)
        .map(|dir| dir.join(name))
        .find(|candidate| candidate.exists())
}

/// Lean module names are capitalized identifiers; requirement ids are not.
pub fn module_name(req_id: &str) -> String {
    let mut out = String::from("Drt");
    let mut capitalize = true;
    for ch in req_id.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize {
                out.extend(ch.to_uppercase());
                capitalize = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize = true;
        }
    }
    out
}

/// The package name a lakefile declares, which is not always its directory
/// name.
///
/// `require` matches on the declared name: the example project lives in
/// `formal/` but declares `name = "checkout-model"`, and requiring it as
/// `formal` fails with "package «checkout-model» was required as 'formal'".
pub fn lake_package_name(package_root: &Path) -> Option<String> {
    if let Ok(toml) = std::fs::read_to_string(package_root.join("lakefile.toml")) {
        for line in toml.lines() {
            let line = line.trim();
            let Some(rest) = line.strip_prefix("name") else { continue };
            let Some(value) = rest.trim_start().strip_prefix('=') else { continue };
            let value = value.trim().trim_matches('"').trim_matches('\'').trim();
            if !value.is_empty() {
                return Some(value.to_string());
            }
        }
    }
    if let Ok(lean) = std::fs::read_to_string(package_root.join("lakefile.lean")) {
        for line in lean.lines() {
            let Some(rest) = line.trim().strip_prefix("package ") else { continue };
            let name = rest
                .split_whitespace()
                .next()
                .unwrap_or("")
                .trim_matches(|c| c == '\u{ab}' || c == '\u{bb}');
            if !name.is_empty() {
                return Some(name.to_string());
            }
        }
    }
    None
}

/// Quote a package name for a `require`, so a hyphenated name stays one token.
fn lean_ident(name: &str) -> String {
    if !name.is_empty()
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !name.starts_with(|c: char| c.is_ascii_digit())
    {
        name.to_string()
    } else {
        format!("\u{ab}{name}\u{bb}")
    }
}

/// The lakefile for the generated package.
pub fn lakefile(project_name: &str, model_package_path: &str, module: &str) -> String {
    let project_name = lean_ident(project_name);
    format!(
        r#"import Lake
open Lake DSL

-- Generated by TraceLean. Builds a runner that speaks the differential-testing
-- protocol: one JSON case per line in, one JSON reply per line out.
package drt where

require {project_name} from "{model_package_path}"

lean_lib {module} where

@[default_target]
lean_exe drtRunner where
  root := `{module}
"#
    )
}

/// The runner module: decode, dispatch, encode, flush.
///
/// The flush is not optional — Lean's stdout is block-buffered on a pipe, so
/// without it the first case never reaches the comparator and the run hangs.
pub fn runner_source(module: &str, imports: &[String], opens: &[String], dispatch: &str) -> String {
    let import_lines = imports
        .iter()
        .map(|i| format!("import {i}"))
        .collect::<Vec<_>>()
        .join("\n");
    // The model's own namespaces are opened so the dispatch can name its
    // argument *types* -- `Order`, not `Checkout.Order` -- which is the form
    // they are written in at the definition and therefore the form read out of
    // it. Functions stay fully qualified, so an ambiguity between two opened
    // namespaces is a compile error in one place rather than a wrong call.
    let open_lines = opens
        .iter()
        .map(|o| format!("open {o}"))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"{import_lines}
import Lean.Data.Json

open Lean
{open_lines}

namespace {module}

/-- One generated case. -/
structure Case where
  case : Nat
  op : String
  input : Json
  deriving FromJson, ToJson

/-- Dispatch a case to the model. Generated from the requirement's binding. -/
def handle (c : Case) : Except String Json :=
{dispatch}

def replyJson (id : Nat) (result : Except String Json) : Json :=
  match result with
  | .ok output => Json.mkObj [("case", toJson id), ("output", output)]
  | .error message => Json.mkObj [("case", toJson id), ("error", toJson message)]

partial def loop (stdin : IO.FS.Stream) (stdout : IO.FS.Stream) : IO Unit := do
  let line ← stdin.getLine
  if line.isEmpty then
    return ()
  let trimmed := line.trim
  if trimmed.isEmpty then
    loop stdin stdout
  else
    let reply :=
      match Json.parse trimmed >>= fromJson? (α := Case) with
      | .ok c => replyJson c.case (handle c)
      | .error e => Json.mkObj [("case", toJson (0 : Nat)), ("error", toJson s!"bad case: {{e}}")]
    stdout.putStrLn reply.compress
    -- Block-buffered pipe: without this flush the comparator waits forever.
    stdout.flush
    loop stdin stdout

def main : IO Unit := do
  let stdin ← IO.getStdin
  let stdout ← IO.getStdout
  loop stdin stdout

end {module}

def main : IO Unit := {module}.main
"#
    )
}

/// Module name of the project-wide runner.
///
/// There is one runner binary for the whole project, not one per requirement:
/// `package_dir` is a single directory, so generating per requirement
/// overwrote the previous requirement's module while every binding's
/// `model.cmd` still pointed at the one `drtRunner` path. One module holding
/// every entry point, dispatched by `op`, is what that path can honestly mean.
pub const PROJECT_MODULE: &str = "DrtModel";

/// Write the generated package to disk. Returns the package directory.
pub fn generate(
    root: &Path,
    req_id: &str,
    model_package_path: &str,
    model_package_name: &str,
    imports: &[String],
    opens: &[String],
    dispatch: &str,
) -> Result<PathBuf, String> {
    generate_with_module(
        root,
        &module_name(req_id),
        model_package_path,
        model_package_name,
        imports,
        opens,
        dispatch,
    )
}

/// Write the generated package to disk under an explicit module name.
pub fn generate_with_module(
    root: &Path,
    module: &str,
    model_package_path: &str,
    model_package_name: &str,
    imports: &[String],
    opens: &[String],
    dispatch: &str,
) -> Result<PathBuf, String> {
    let dir = package_dir(root);
    std::fs::create_dir_all(&dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;

    let module = module.to_string();
    std::fs::write(
        dir.join("lakefile.lean"),
        lakefile(model_package_name, model_package_path, &module),
    )
    .map_err(|e| format!("writing lakefile: {e}"))?;

    std::fs::write(
        dir.join(format!("{module}.lean")),
        runner_source(&module, imports, opens, dispatch),
    )
        .map_err(|e| format!("writing runner module: {e}"))?;

    Ok(dir)
}

/// Every `require <name> from "<path>"` in a lakefile, as `(name, path)`.
pub fn requires_in(lakefile: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for line in lakefile.lines() {
        let Some(rest) = line.trim().strip_prefix("require ") else { continue };
        let Some((name, tail)) = rest.split_once(" from ") else { continue };
        let name = name.trim().trim_matches(|c| c == '\u{ab}' || c == '\u{bb}').to_string();
        let path = tail.trim().trim_matches('"').to_string();
        if !name.is_empty() && !path.is_empty() {
            out.push((name, path));
        }
    }
    out
}

/// Refuse to run `lake build` when a `require` names a package differently
/// from the way that package names itself.
///
/// This is not tidiness. Lake 4.12 answers that mismatch by **deleting the
/// required package's source directory** — it reports
/// `package '«checkout-model»' was required as 'formal'` and, on the way to
/// that message, removes `formal/`. It cost this project its entire Lean model
/// once. The name is derived correctly now (`lake_package_name`), so this check
/// should never fire; it exists because the failure mode is silent data loss in
/// a directory TraceLean does not own, and a check that never fires is a cheap
/// price for that.
pub fn check_requires(dir: &Path) -> Result<(), String> {
    let Ok(lakefile) = std::fs::read_to_string(dir.join("lakefile.lean")) else {
        return Ok(());
    };
    for (name, relative) in requires_in(&lakefile) {
        let target = dir.join(&relative);
        let Some(declared) = lake_package_name(&target) else { continue };
        if declared != name {
            return Err(format!(
                "Refusing to build: the generated lakefile requires `{name}` from {relative}, \
                 but that package declares itself `{declared}`. Lake answers this mismatch by \
                 deleting {}, so the build is not attempted. Regenerate the runner.",
                target.display()
            ));
        }
    }
    Ok(())
}

/// Build the generated package and return the runner binary's path.
pub fn build(root: &Path) -> Result<PathBuf, String> {
    let toolchain = toolchain()?;
    let dir = package_dir(root);
    if !dir.exists() {
        return Err(format!(
            "No generated runner at {} — generate it before building.",
            dir.display()
        ));
    }
    check_requires(&dir)?;

    let output = std::process::Command::new(&toolchain.lake)
        .arg("build")
        .current_dir(&dir)
        .output()
        .map_err(|e| format!("running lake build: {e}"))?;

    if !output.status.success() {
        return Err(format!(
            "lake build failed:\n{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    binary_path(root).ok_or_else(|| {
        "lake build succeeded but no `drtRunner` binary was found under \
         .lake/build/bin or build/bin"
            .to_string()
    })
}

/// Lean ≥ 4.3 builds into `.lake/build/bin`; older versions use `build/bin`.
pub fn binary_path(root: &Path) -> Option<PathBuf> {
    let dir = package_dir(root);
    for candidate in [
        dir.join(".lake/build/bin/drtRunner"),
        dir.join("build/bin/drtRunner"),
    ] {
        if candidate.exists() {
            return Some(candidate);
        }
    }
    None
}

// --- Deriving the runner from a `@models` anchor -------------------------

/// What the generated runner needs to know about a model definition.
#[derive(Debug, Clone, PartialEq)]
pub struct ModelEntry {
    /// Lean module to import, derived from the file path.
    pub module: String,
    /// Fully-qualified name of the function to call.
    pub function: String,
    /// The `op` that selects this entry point.
    pub op: String,
    /// Argument names, in order, read out of the declaration.
    pub arguments: Vec<String>,
    /// Argument types, in the same order. Empty when they could not be read.
    pub argument_types: Vec<String>,
    /// Decode the whole `input` as the single argument rather than reading
    /// fields out of it by name.
    ///
    /// `infer_input` flattens a lone structure argument -- a model taking one
    /// `Order` gets the schema of `Order` itself, not `{"o": {...}}`, because
    /// that is the natural reading and what a hand-written binding does. The
    /// dispatch has to flatten it the same way or it asks for a field named
    /// after the binder and never finds one.
    pub whole_input: bool,
}

/// Lean modules are named after their path relative to the package root, with
/// separators as dots: `Auth/Login.lean` imports as `Auth.Login`.
pub fn module_for_path(relative: &std::path::Path) -> Option<String> {
    let stem_path = relative.with_extension("");
    let parts: Vec<String> = stem_path
        .components()
        .filter_map(|c| match c {
            std::path::Component::Normal(s) => s.to_str().map(|s| s.to_string()),
            _ => None,
        })
        .collect();
    if parts.is_empty() {
        return None;
    }
    Some(parts.join("."))
}

/// Read the name and argument list out of a Lean declaration.
///
/// Deliberately shallow: it handles `def f (a : T) (b : U) : R :=` and the
/// `theorem`/`abbrev` forms, and gives up on anything more exotic rather than
/// guessing. A wrong guess would produce a runner that compiles and answers the
/// wrong question, which is worse than refusing.
pub fn parse_declaration(source: &str) -> Option<(String, Vec<String>)> {
    let mut name = None;
    let mut arguments = Vec::new();

    for line in source.lines() {
        let trimmed = line.trim_start();
        let rest = ["def ", "abbrev ", "partial def "]
            .iter()
            .find_map(|kw| trimmed.strip_prefix(kw));
        let Some(rest) = rest else { continue };

        let mut chars = rest.char_indices();
        let end = chars
            .find(|(_, c)| c.is_whitespace() || *c == '(' || *c == ':' || *c == '{')
            .map(|(i, _)| i)
            .unwrap_or(rest.len());
        let declared = rest[..end].trim();
        if declared.is_empty() {
            continue;
        }
        name = Some(declared.to_string());

        // Binder groups: `(a b : T)` contributes two arguments.
        let mut remaining = &rest[end..];
        while let Some(open) = remaining.find(['(', '{']) {
            let closer = if remaining.as_bytes()[open] == b'(' { ')' } else { '}' };
            let Some(close) = remaining[open..].find(closer) else { break };
            let group = &remaining[open + 1..open + close];
            if let Some((names, _ty)) = group.split_once(':') {
                for n in names.split_whitespace() {
                    arguments.push(n.to_string());
                }
            }
            remaining = &remaining[open + close + 1..];
            if remaining.trim_start().starts_with(':') {
                break; // reached the return type
            }
        }
        break;
    }

    name.map(|n| (n, arguments))
}

/// Build a `ModelEntry` from a `@models` link and the file it points into.
pub fn entry_from_link(
    link: &crate::trace::Link,
    file_source: &str,
    op: &str,
) -> Result<ModelEntry, String> {
    let relative = link.anchor.file.clone();
    entry_from_link_relative(link, file_source, op, &relative)
}

/// As `entry_from_link`, with the module name taken from `relative` rather than
/// from the anchor's project-relative path.
///
/// Lean names a module after its path from the **lake package** root, not from
/// the project root: the example's model is `formal/Checkout.lean` in the
/// project and `Checkout` to Lean, because `formal/` is where the lakefile
/// lives. Importing it as `formal.Checkout` fails with "unknown module prefix".
pub fn entry_from_link_relative(
    link: &crate::trace::Link,
    file_source: &str,
    op: &str,
    relative: &std::path::Path,
) -> Result<ModelEntry, String> {
    let module = module_for_path(relative)
        .ok_or_else(|| format!("cannot derive a Lean module name from {}", relative.display()))?;

    let anchored = anchored_source(file_source, link);
    let (name, arguments) = parse_declaration(&anchored).ok_or_else(|| {
        format!(
            "could not read a `def` out of the anchor at {}:{} — \
             write the dispatch by hand in .tracelean/drt.json for this binding",
            link.anchor.file.display(),
            link.anchor.start_line + 1
        )
    })?;

    let prefix = namespace_prefix(file_source, link.anchor.start_line as usize);
    let function = match &prefix {
        Some(prefix) => format!("{prefix}.{name}"),
        None => name.clone(),
    };
    let argument_types = super::infer::parse_binders(file_source, &name)
        .map(|binders| binders.into_iter().map(|(_, ty)| ty).collect())
        .unwrap_or_default();

    Ok(ModelEntry {
        module,
        function,
        op: op.to_string(),
        arguments,
        argument_types,
        whole_input: false,
    })
}

/// The `namespace` prefix in force at `line`, as Lean would resolve it.
///
/// The runner imports the model's module rather than `open`ing it, so it has to
/// name declarations in full: the example's model is `Checkout.discountCents`,
/// and calling it `discountCents` fails to elaborate with "unknown identifier".
/// The tree-sitter grammar is no help here -- it parses `namespace Foo` and its
/// matching `end Foo` as two flat sibling nodes rather than one region -- so the
/// nesting is recovered from the source directly.
pub fn namespace_prefix(source: &str, line: usize) -> Option<String> {
    let mut stack: Vec<Option<String>> = Vec::new();
    for raw in source.lines().take(line) {
        let trimmed = raw.trim();
        if let Some(rest) = trimmed.strip_prefix("namespace ") {
            let name = rest.split_whitespace().next().unwrap_or("");
            if !name.is_empty() {
                stack.push(Some(name.to_string()));
            }
        } else if trimmed == "section" || trimmed.starts_with("section ") {
            // A section scopes variables, not names, so it contributes nothing
            // to a qualified name -- but its `end` still has to be matched.
            stack.push(None);
        } else if trimmed == "end" || trimmed.starts_with("end ") {
            stack.pop();
        }
    }
    let parts: Vec<String> = stack.into_iter().flatten().collect();
    (!parts.is_empty()).then(|| parts.join("."))
}

fn anchored_source(content: &str, link: &crate::trace::Link) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let start = (link.anchor.start_line as usize).min(lines.len());
    let end = ((link.anchor.end_line as usize) + 1).min(lines.len());
    lines[start..end].join("\n")
}

/// The `handle` body: decode the input, call the model, encode the answer.
///
/// Arguments are read out of the input object by name, so the declared schema's
/// field names and the model's binder names have to agree — which is checkable,
/// unlike positional arguments, and produces a readable error when they do not.
pub fn dispatch_for(entries: &[ModelEntry]) -> String {
    if entries.is_empty() {
        return "  .error \"no model entry points are configured for this requirement\"".into();
    }

    let mut out = String::from("  match c.op with\n");
    for entry in entries {
        out.push_str(&format!("  | \"{}\" =>\n", entry.op));
        if entry.arguments.is_empty() {
            out.push_str(&format!("    .ok (toJson ({}))\n", entry.function));
            continue;
        }
        if entry.whole_input {
            let argument = &entry.arguments[0];
            let ty = entry.argument_types.first().cloned().unwrap_or_else(|| "_".into());
            out.push_str(&format!("    match fromJson? (\u{3b1} := {ty}) c.input with\n"));
            out.push_str("    | .error e => .error s!\"input: {e}\"\n");
            out.push_str(&format!("    | .ok {argument} =>\n"));
            out.push_str(&format!("    .ok (toJson ({} {argument}))\n", entry.function));
            continue;
        }
        for argument in &entry.arguments {
            out.push_str(&format!(
                "    match c.input.getObjValAs? _ \"{argument}\" with\n    \
                 | .error e => .error s!\"argument `{argument}`: {{e}}\"\n    | .ok {argument} =>\n"
            ));
        }
        out.push_str(&format!(
            "    .ok (toJson ({} {}))\n",
            entry.function,
            entry.arguments.join(" ")
        ));
    }
    out.push_str("  | other => .error s!\"unknown op: {other}\"");
    out
}
