//! Evidence: what a link is actually worth, and why.
//!
//! An annotation is a claim; evidence is what backs it. Records are written by
//! the backends (the judge, differential testing, Lean proofs) and are only
//! ever *invalidated* by the scanner — never regenerated by it.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

fn default_source() -> String {
    "api".to_string()
}

/// Which of the three bonds a record is about.
///
/// Keeping these separate is what makes the weakest-link rule expressible: a
/// proved model with an unbound implementation must render as
/// `L4 model · L1 code`, not as a single reassuring badge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Bond {
    /// Requirement text ↔ Lean model. Checked by the judge.
    RequirementModel,
    /// Lean model ↔ implementation. Checked by differential testing.
    ModelImpl,
    /// A property of the model, proved in Lean.
    ModelProof,
}

impl Bond {
    pub fn as_str(&self) -> &'static str {
        match self {
            Bond::RequirementModel => "requirement-model",
            Bond::ModelImpl => "model-impl",
            Bond::ModelProof => "model-proof",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Level {
    /// The annotation resolves. Nothing has been checked.
    L1,
    /// Requirement and model judged consistent, witness execution passing.
    L2,
    /// Differential testing passes, with a stated case count and coverage.
    L3,
    /// A Lean theorem discharges the property.
    L4,
}

impl Level {
    pub fn as_str(&self) -> &'static str {
        match self {
            Level::L1 => "L1",
            Level::L2 => "L2",
            Level::L3 => "L3",
            Level::L4 => "L4",
        }
    }
}

/// What a record is about: one clause of one requirement, on one bond.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct EvidenceKey {
    pub req_id: String,
    pub clause: Option<String>,
    pub bond: Bond,
}

/// Backend-specific detail. Typed rather than free-form JSON so that a record
/// cannot quietly omit the things that make it reproducible.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "backend", rename_all = "lowercase")]
pub enum EvidenceDetail {
    Judge {
        verdict: String,
        prompt_version: String,
        model_id: String,
        /// `Some(true)` when the witness was executed against the compiled
        /// model and behaved as claimed; `Some(false)` when it was falsified;
        /// `None` when there was nothing to check.
        witness_confirmed: Option<bool>,
        /// True when no model runner was available, so the verdict could not
        /// be checked by execution. A degraded verdict never produces a drift
        /// finding — it records what was said, not what was established.
        ///
        /// Defaulted because the lockfile is persisted and older records must
        /// keep parsing.
        #[serde(default)]
        degraded: bool,
        #[serde(default)]
        confidence: String,
        /// How the verdict reached us: `"api"` when a provider was called,
        /// `"pasted"` when a person ran the prompt elsewhere and pasted the
        /// reply back.
        ///
        /// Recorded because "who produced this verdict" is part of what an
        /// evidence record is for. It changes nothing about how much the
        /// verdict is worth — a pasted reply is parsed and its witness executed
        /// by the same code path — but a reader six months from now is entitled
        /// to know.
        #[serde(default = "default_source")]
        source: String,
        /// How the witness claim was compared — recorded so a verdict can be
        /// re-read later without guessing.
        #[serde(default)]
        comparison_mode: String,
        #[serde(default)]
        cost_usd: f64,
    },
    Drt {
        seed: u64,
        cases: usize,
        divergences: usize,
        coverage_covered: usize,
        coverage_total: usize,
        lean_version: String,
    },
    Proof {
        theorem: String,
        lean_version: String,
    },
}

impl EvidenceDetail {
    pub fn backend(&self) -> &'static str {
        match self {
            EvidenceDetail::Judge { .. } => "judge",
            EvidenceDetail::Drt { .. } => "drt",
            EvidenceDetail::Proof { .. } => "lean",
        }
    }
}

/// One piece of evidence.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EvidenceRecord {
    pub key: EvidenceKey,
    pub level: Level,
    /// Every input this verdict depended on: `"model"`, `"impl"`, `"adapter"`,
    /// `"clause"` → hash at the time the record was written.
    ///
    /// Staleness is "any of these disagrees with the current hash". A single
    /// anchor hash would miss model-side edits entirely.
    pub input_hashes: BTreeMap<String, String>,
    pub detail: EvidenceDetail,
    /// RFC3339 timestamp.
    pub at: String,
    /// Undo-tree node of the command that produced it, when there was one.
    pub node: Option<String>,
}

impl EvidenceRecord {
    /// Which inputs no longer match. Empty means the record still stands.
    pub fn stale_inputs(&self, current: &BTreeMap<String, String>) -> Vec<String> {
        self.input_hashes
            .iter()
            .filter(|(k, v)| current.get(*k).map(|c| c != *v).unwrap_or(true))
            .map(|(k, _)| k.clone())
            .collect()
    }
}

/// The assurance of one clause: a level per bond, never collapsed into one
/// number. Rendering joins them (`L4 model · L1 code`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Assurance {
    pub requirement_model: Option<Level>,
    pub model_impl: Option<Level>,
    pub model_proof: Option<Level>,
    /// Bonds whose evidence exists but has gone stale.
    pub stale: Vec<Bond>,
}

impl Assurance {
    /// The weakest link across the bonds that exist, which is what governs how
    /// much the chain as a whole is worth.
    pub fn weakest(&self) -> Level {
        [self.requirement_model, self.model_impl, self.model_proof]
            .into_iter()
            .flatten()
            .min()
            .unwrap_or(Level::L1)
    }

    pub fn set(&mut self, bond: Bond, level: Level) {
        match bond {
            Bond::RequirementModel => self.requirement_model = Some(level),
            Bond::ModelImpl => self.model_impl = Some(level),
            Bond::ModelProof => self.model_proof = Some(level),
        }
    }
}
