//! The TypeScript runner, as a thing rather than as a function.
//!
//! Most of what `REQ-DRT-TS` asks is about the shape of the arrangement — what
//! is generated, where it is written, what it imports, what happens when the
//! implementation throws. None of those is a function from a value to a value,
//! so each is established by reading the tree and by running the thing, which
//! is what `@structural` records (ADR-0012).

use std::collections::BTreeMap;
use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};

use tracelean_core::drt::ts_runner;
use tracelean_core::drt::{Binding, CallSpec};

fn project_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().parent().unwrap().to_path_buf()
}

fn scratch(name: &str) -> PathBuf {
    let path = std::env::temp_dir().join(format!("tracelean-ts-{name}"));
    let _ = std::fs::remove_dir_all(&path);
    path
}

fn binding(entry: &str) -> Binding {
    Binding {
        req_id: "REQ-VIEW".into(),
        clause: Some("rendering_is_total".into()),
        op: None,
        also_checks: Vec::new(),
        also_implemented_by: Vec::new(),
        floors: Vec::new(),
        waive: Vec::new(),
        model: None,
        implementation: CallSpec {
            language: "typescript".into(),
            entry: entry.into(),
            params: BTreeMap::new(),
        },
    }
}

/// Generation writes the runner and nothing else, under the cache directory.
///
/// A generator that could write into the project would be a tool that edits
/// what it is checking.
///
/// @tests REQ-DRT-TS.generated
/// @tests REQ-DRT-TS.project_untouched
/// @tests REQ-DRT-TS.runs_the_shipped_source
/// @structural REQ-DRT-TS.generated reason="a claim that a file is produced by this tool rather than maintained, which is read off the tree rather than computed"
/// @structural REQ-DRT-TS.project_untouched reason="a claim about which paths a generator writes to, which is a property of the run and not of any value"
/// @structural REQ-DRT-TS.runs_the_shipped_source reason="a claim that the file executed is the project's own source, read off what the generated runner imports"
#[test]
fn the_runner_is_generated_under_the_cache_and_imports_the_project_itself() {
    let root = project_root();
    let into = scratch("generated");
    let spec = binding("web/src/view.ts::plainText");
    let entry = ts_runner::resolve(&root, &spec, &spec.implementation).expect("it resolves");
    let dir = ts_runner::materialize(&into, &[entry]).expect("generated");

    assert_eq!(dir, ts_runner::package_dir(&into));
    assert!(dir.starts_with(into.join(".tracelean")), "{}", dir.display());

    // Exactly two files, both generated, neither the project's.
    let mut written: Vec<String> = std::fs::read_dir(&dir)
        .expect("the runner directory")
        .flatten()
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    written.sort();
    assert_eq!(written, vec!["package.json".to_string(), "runner.ts".to_string()]);

    let source = std::fs::read_to_string(dir.join("runner.ts")).expect("the runner");
    assert!(source.starts_with("// Generated by TraceLean"), "{source}");

    // What it imports is the project's own file — not a copy of it, and not
    // something a build step produced.
    let imported = root.join("web/src/view.ts");
    assert!(
        source.contains(&imported.display().to_string()),
        "the runner does not import {}:\n{source}",
        imported.display()
    );
    assert!(imported.exists(), "the imported file is the one that ships");

    // And regenerating changes nothing, so a stale runner is the only reason a
    // file here would ever differ.
    let before = std::fs::read_to_string(dir.join("runner.ts")).unwrap();
    let entry = ts_runner::resolve(&root, &spec, &spec.implementation).unwrap();
    ts_runner::materialize(&into, &[entry]).unwrap();
    assert_eq!(before, std::fs::read_to_string(dir.join("runner.ts")).unwrap());

    let _ = std::fs::remove_dir_all(&into);
}

/// An implementation that throws is one case's error, not the end of the run.
///
/// Nothing typechecks a TypeScript call, so a binding that does not fit is a
/// thrown exception. If that ended the runner, the divergence reported would be
/// "the process died" for every case after it — which names the wrong problem
/// and hides every later one.
///
/// @tests REQ-DRT-TS.failure_is_an_answer
/// @structural REQ-DRT-TS.failure_is_an_answer reason="a claim about what a live process does after its implementation throws, which no pair of values expresses"
#[test]
#[ignore = "runs node; run with --ignored"]
fn an_implementation_that_throws_answers_and_keeps_going() {
    let into = scratch("throwing");
    std::fs::create_dir_all(&into).unwrap();
    let module = into.join("throws.ts");
    std::fs::write(
        &module,
        "export function boom(x: number): number {\n  \
         if (x === 1) throw new Error(\"no\");\n  return x;\n}\n",
    )
    .unwrap();

    let entry = ts_runner::Entry {
        op: "REQ-X.c".into(),
        module: module.display().to_string(),
        symbol: "boom".into(),
        parameters: vec!["x".into()],
        sources: vec!["x".into()],
    };
    let dir = ts_runner::materialize(&into, &[entry]).expect("generated");

    let mut child = std::process::Command::new("node")
        .arg(dir.join("runner.ts"))
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()
        .expect("node runs");
    let mut stdin = child.stdin.take().unwrap();
    let mut stdout = std::io::BufReader::new(child.stdout.take().unwrap());

    for (case, x) in [(0u64, 0), (1, 1), (2, 2)] {
        writeln!(stdin, "{{\"case\":{case},\"op\":\"REQ-X.c\",\"input\":{{\"x\":{x}}}}}").unwrap();
    }
    stdin.flush().unwrap();

    let mut replies = Vec::new();
    for _ in 0..3 {
        let mut line = String::new();
        stdout.read_line(&mut line).expect("a reply");
        replies.push(serde_json::from_str::<serde_json::Value>(&line).expect("JSON"));
    }
    let _ = child.kill();

    assert_eq!(replies[0]["output"], 0, "{:?}", replies[0]);
    assert_eq!(replies[1]["error"], "no", "a throw must be this case's error: {:?}", replies[1]);
    // The one that matters: the run continued.
    assert_eq!(replies[2]["output"], 2, "the runner stopped after a throw: {:?}", replies[2]);

    let _ = std::fs::remove_dir_all(&into);
}

/// Every second implementation is compared against the model, never against the
/// first.
///
/// Two implementations checked against each other agree perfectly when both are
/// wrong, so the arrangement matters more than any one run: a binding's extra
/// implementations sit beside the first under one `model`, and the suite that
/// drives them names the Lean function on the other side.
///
/// @tests REQ-DRT-TS.second_implementation_same_oracle
/// @structural REQ-DRT-TS.second_implementation_same_oracle reason="a claim about what each implementation is compared against, which is a property of the binding file and the suites rather than of a value"
#[test]
fn a_second_implementation_is_checked_against_the_model() {
    let root = project_root();
    let text = std::fs::read_to_string(root.join(".tracelean/drt.json")).expect("drt.json");
    let config: serde_json::Value = serde_json::from_str(&text).expect("readable JSON");

    let mut seconds = 0;
    for binding in config["bindings"].as_array().expect("bindings") {
        let Some(more) = binding["also_implemented_by"].as_array() else { continue };
        if more.is_empty() {
            continue;
        }
        seconds += more.len();
        // The model is what they are all measured against, and there is exactly
        // one of it.
        assert!(
            binding["model"]["function"].is_string(),
            "a binding with a second implementation and no model: {binding}"
        );
        for implementation in more {
            assert_ne!(
                implementation["language"], binding["implementation"]["language"],
                "a second implementation in the same language is a copy, not a check"
            );
        }
    }
    assert!(seconds >= 3, "only {seconds} second implementations; this checked little");

    // And no suite compares one implementation to another: every differential
    // run takes a model runner and an implementation runner.
    let suite = std::fs::read_to_string(root.join("crates/core/tests/differential_typescript.rs"))
        .expect("the TypeScript suite");
    assert!(
        suite.contains("harness::lean_runner"),
        "the TypeScript suite must compare against the model"
    );
    for line in suite.lines() {
        let line = line.trim();
        if line.starts_with("//") {
            continue;
        }
        assert!(
            !(line.contains("harness::ts_runner") && line.contains("harness::rust_runner")),
            "a suite comparing two implementations to each other: {line}"
        );
    }
}
